# Generated by Django 3.2.9 on 2021-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comment_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
