# Generated by Django 3.2.9 on 2021-11-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie.Genre'),
        ),
    ]
