# Generated by Django 3.2.9 on 2021-11-19 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0003_auto_20211118_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rank',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.ManyToManyField(null=True, related_name='movies', through='movie.Rates', to=settings.AUTH_USER_MODEL),
        ),
    ]
