# Generated by Django 3.2.9 on 2021-11-19 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_auto_20211119_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movie.Rates', to=settings.AUTH_USER_MODEL),
        ),
    ]
